<?php

/**
 * @file
 * Contains intercept_equipment.module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Database\Database;

/**
 * Implements hook_node_access().
 */
function intercept_equipment_node_access(\Drupal\node\NodeInterface $node, $op, \Drupal\Core\Session\AccountInterface $account) {
  if ($node->bundle() == 'equipment' && $op == 'view') {
    return AccessResult::forbiddenIf(!$account->hasPermission('view reservation content'))
      ->cachePerPermissions()
      ->cachePerUser()
      ->addCacheableDependency($node);
  }
   // No opinion.
  return AccessResult::neutral();
}

/**
 * Implements hook_update_N().
 * 
 * Install temporary database table so that we can uninstall and reinstall
 * module with new equipment reservation entity.
 */
function intercept_equipment_update_8001() {
  $spec = array(
    'description' => 'Equipment Reservations',
    'fields' => array(
      'id' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'vid' => array(
        'type' => 'int',
        'length' => 11,
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array('id'),
  ); 
  $schema = Database::getConnection()->schema();
  if ($schema->tableExists('equipment_reservation') == FALSE) {
    $schema->createTable('equipment_reservation', $spec);
  }
}
