<?php

namespace Drupal\intercept_location\Form;

use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\polaris\Client;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\intercept_location\LocationListBuilder;

class SettingsForm extends ConfigFormBase {

  private $entityTypeManager;

  private $client;

  /**
   * Constructs a \Drupal\system\ConfigFormBase object.
   *
   * @param \Drupal\Core\Config\ConfigFactoryInterface $config_factory
   *   The factory for configuration objects.
   */
  public function __construct(ConfigFactoryInterface $config_factory, EntityTypeManagerInterface $entity_type_manager, Client $client) {
    $this->setConfigFactory($config_factory);
    $this->entityTypeManager = $entity_type_manager;
    $this->client = $client;
  }

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container) {
    return new static(
      $container->get('config.factory'),
      $container->get('entity_type.manager'),
      $container->get('polaris.client')
    );
  }

  protected function getEditableConfigNames() {
    return ['intercept.settings'];
  }

  public function getFormId() {
    return 'intercept_location_settings';
  }

  public function buildForm(array $form, FormStateInterface $form_state) {
    $settings = $this->config('intercept_core.settings')->get('location');
    $form['mapping_enabled'] = [
      '#title' => $this->t('Enable ILS location mapping'),
      '#type' => 'checkbox',
      '#default_value' => !empty($settings['mapping_enabled']),
    ];
    $form['mapping_integration_type'] = [
      '#title' => $this->t('Import organizations as locations from Polaris'),
      '#type' => 'select',
      '#options' => [
        'once' => $this->t('Run once'),
        'cron' => $this->t('Run regularly with cron'),
      ],
      '#default_value' => isset($settings['mapping_integration_type']) ? $settings['mapping_integration_type'] : NULL,
    ];
    $entity_type = $this->entityTypeManager->getDefinition('node');
    $form['list'] = $this->entityTypeManager->createHandlerInstance(LocationListBuilder::class, $entity_type)->render();

    $form['actions']['import'] = [
      '#type' => 'submit',
      '#value' => $this->t('Run import'),
      '#weight' => 10,
      '#submit' => [$this, '::runImport'],
    ];

    $form['actions']['delete'] = [
      '#type' => 'submit',
      '#value' => $this->t('Remove mapped locations'),
      '#weight' => 11,
      '#submit' => [$this, '::runDelete'],
      '#attributes' => ['class' => ['button--danger']],
    ];

    return parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  public function runImport(array &$form, FormStateInterface $form_state) {
    $config = $this->config('intercept_core.settings')->get('location');
    if (!empty($config['mapping_enabled'])) {
      \Drupal::service('intercept_ils.mapping')->pullOrganizations();
    }
  }

  public function runDelete(array &$form, FormStateInterface $form_state) {
    $storage = $this->entityTypeManager->getStorage('node');
    $nodes = $storage->getQuery()
      ->condition('field_ils_id', NULL, 'IS NOT')
      ->condition('type', 'location', '=')
      ->execute();
    $nodes = $storage->loadMultiple(array_values($nodes));
    $storage->delete($nodes);
  }

  public function submitForm(array &$form, FormStateInterface $form_state) {
    $values = $form_state->cleanValues()->getValues();
    $config = $this->config('intercept_core.settings');
    $config->set('location', $values);
    $config->save();
    parent::submitForm($form, $form_state);
  }

}
