<?php

/**
 * Implements hook_preprocess_page.
 */
function intercept_core_preprocess_page(array &$variables) {
  $consumer_id = Drupal::state()->get('intercept_client.id');
  $consumer = Drupal::service('entity_type.manager')->getStorage('consumer')->load($consumer_id);
  if ($consumer) {
    $consumer_token = $consumer ? $consumer->uuid() : NULL;
    $variables['#attached']['drupalSettings']['intercept']['consumer'] = $consumer_token;
  }
}
