<?php

/**
 * @file
 * Contains intercept_room_reservation.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\Element;
use Drupal\intercept_room_reservation\Entity\RoomReservationInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_help().
 */
function intercept_room_reservation_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the intercept_room_reservation module.
    case 'help.page.intercept_room_reservation':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Room reservation functionality for the InterCEPT library') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function intercept_room_reservation_theme() {
  return [
    'room_reservation' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for Room reservation templates.
 *
 * Default template: room_reservation.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_room_reservation(array &$variables) {
  // Fetch RoomReservation Entity Object.
  $room_reservation = $variables['room_reservation'] = $variables['elements']['#room_reservation'];
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  $variables['label'] = $room_reservation->label();
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function intercept_room_reservation_theme_suggestions_room_reservation(array $variables) {
  $suggestions = [];
  $room_reservation = $variables['elements']['#room_reservation'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'room_reservation__' . $sanitized_view_mode;
  $suggestions[] = 'room_reservation__' . $room_reservation->bundle();
  $suggestions[] = 'room_reservation__' . $room_reservation->bundle() . '__' . $sanitized_view_mode;

  return $suggestions;
}

/**
 * Implements hook_entity_extra_field_info().
 */
function intercept_room_reservation_entity_extra_field_info() {
  $extra = [];

  $extra['room_reservation']['room_reservation']['display']['location_full'] = [
    'label' => t('Full location'),
    'description' => t('Location title and room name'),
    'weight' => 10,
    'visible' => FALSE,
  ];

  $extra['room_reservation']['room_reservation']['display']['attendees_full'] = [
    'label' => t('Attendee count'),
    'description' => t('Atendee count and label'),
    'weight' => 15,
    'visible' => FALSE,
  ];
  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view()().
 */
function intercept_room_reservation_room_reservation_view(array &$build, RoomReservationInterface $room_reservation, EntityViewDisplayInterface $display, $view_mode) {
  $build['location_full'] = [
    '#type' => 'html_tag',
    '#tag' => 'div',
    '#attributes' => ['class' => 'field-location-full'],
    '#value' => t('At @location @room', [
      '@location' => $room_reservation->get('location')->entity ? $room_reservation->get('location')->entity->label() : '',
      '@room' => $room_reservation->get('field_room')->entity ? $room_reservation->get('field_room')->entity->label() : '',
    ]),
   ];

  $count = $room_reservation->field_attendee_count->getString();
  $build['attendees_full'] = [
    '#type' => 'html_tag',
    '#tag' => 'div',
    '#attributes' => ['class' => 'field-attendees-full'],
    '#value' => !empty($count) ? t('@count Attendees', [
      '@count' => $count,
    ]) : '',
   ];

}
